from __future__ import annotations

"""
phase4/gmail_draft.py — Phase 4D: Create Gmail draft via Gmail API (OAuth2).

Why OAuth2 (not Service Account):
  Gmail API does not allow service accounts to create drafts in personal Gmail.
  Service accounts work for Google Docs/Drive but NOT personal Gmail accounts.
  For Gmail, we use OAuth2 with a one-time browser auth — token saved to
  GMAIL_TOKEN_PATH and reused forever (auto-refreshed).

One-time setup:
  1. Google Cloud Console → APIs & Services → Enable "Gmail API"
  2. Credentials → Create OAuth2 Client ID → Desktop app → Download JSON
  3. Save JSON to e.g. ~/.groww/gmail_client_secret.json
  4. Add to .env:
       GMAIL_CLIENT_SECRET=/Users/you/.groww/gmail_client_secret.json
       GMAIL_TOKEN_PATH=/Users/you/.groww/gmail_token.json
  5. First run: browser opens for one-time approval → token saved automatically
  6. All future runs: uses saved token silently (auto-refreshes)

Approval-gated: only called when user clicks "Publish" in the UI.
Creates a DRAFT — never auto-sends. User opens Gmail → Drafts to review & send.
"""

import base64
import logging
import os
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Any

logger = logging.getLogger(__name__)

_SCOPES = ["https://www.googleapis.com/auth/gmail.send"]


# ── Auth ───────────────────────────────────────────────────────────────────────

def _get_gmail_credentials():
    """
    Load OAuth2 credentials for Gmail.
    - First run: opens browser for user approval, saves token.
    - Subsequent runs: loads saved token, auto-refreshes if expired.
    """
    from google.oauth2.credentials import Credentials
    from google_auth_oauthlib.flow import InstalledAppFlow
    from google.auth.transport.requests import Request

    token_path  = os.path.expanduser(os.getenv("GMAIL_TOKEN_PATH", "~/.groww/gmail_token.json"))
    secret_path = os.path.expanduser(os.getenv("GMAIL_CLIENT_SECRET", "~/.groww/gmail_client_secret.json"))

    creds = None

    # Load saved token if it exists
    if os.path.exists(token_path):
        creds = Credentials.from_authorized_user_file(token_path, _SCOPES)

    # Refresh or re-auth if needed
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
            logger.info("Gmail token refreshed automatically")
        else:
            if not os.path.exists(secret_path):
                raise FileNotFoundError(
                    f"Gmail OAuth2 client secret not found at: {secret_path}\n"
                    "See phase4/gmail_draft.py setup instructions."
                )
            flow = InstalledAppFlow.from_client_secrets_file(secret_path, _SCOPES)
            creds = flow.run_local_server(port=0)
            logger.info("Gmail OAuth2 auth complete — browser approval granted")

        # Save token for future runs
        os.makedirs(os.path.dirname(token_path), exist_ok=True)
        with open(token_path, "w") as f:
            f.write(creds.to_json())
        logger.info("Gmail token saved to %s", token_path)

    return creds


# ── Email body ─────────────────────────────────────────────────────────────────

def _build_plain_body(combined: Any) -> str:
    """Build plain-text email body from CombinedReport."""
    wp = combined.weekly_pulse

    themes_block = "\n".join(
        f"  {i}. {t.label} — {t.review_count} reviews | {t.avg_rating:.1f}★ | {t.pct_of_total:.0f}%\n"
        f"     {t.one_line_summary}"
        for i, t in enumerate(wp.themes, 1)
    )
    quotes_block = "\n".join(f'  "{q}"' for q in wp.quotes)
    actions_block = "\n".join(f"  [{i}] {a}" for i, a in enumerate(wp.action_ideas, 1))
    bullets_block = "\n".join(f"  • {b}" for b in combined.explanation_bullets)
    sources_block = "\n".join(f"  {link}" for link in combined.source_links)

    return f"""GROWW Weekly Pulse + Fee Explainer — {wp.week_label}
{'=' * 55}

📊 WEEKLY REVIEW PULSE
Reviews Analysed: {wp.total_reviews_analysed} | Avg Rating: {wp.avg_rating:.1f}★

TOP THEMES
{themes_block}

USER QUOTES
{quotes_block}

ACTION IDEAS
{actions_block}

{'─' * 55}

💰 FEE EXPLANATION: {combined.fee_scenario}
{bullets_block}

Sources:
{sources_block}
Last checked: {combined.last_checked}

{'=' * 55}
Generated by GROWW Weekly Pulse pipeline.
This is a draft — review before sending.
"""


# ── HTML body ──────────────────────────────────────────────────────────────────

def _build_html_body(combined: Any) -> str:
    """Render HTML email using Jinja2 template with fee data passed as variables."""
    from jinja2 import Environment, FileSystemLoader
    import os

    template_dir = os.path.join(os.path.dirname(__file__), "templates")
    env      = Environment(loader=FileSystemLoader(template_dir))
    template = env.get_template("pulse_email.html")

    wp = combined.weekly_pulse

    class _Theme:
        def __init__(self, t):
            self.label            = t.label
            self.review_count     = t.review_count
            self.avg_rating       = t.avg_rating
            self.pct_of_total     = t.pct_of_total
            self.one_line_summary = t.one_line_summary

    class _Pulse:
        def __init__(self):
            self.week_label             = wp.week_label
            self.total_reviews_analysed = wp.total_reviews_analysed
            self.avg_rating             = wp.avg_rating
            self.top_themes             = [_Theme(t) for t in wp.themes]
            self.user_quotes            = wp.quotes
            self.action_ideas           = wp.action_ideas

    return template.render(
        pulse=_Pulse(),
        generated_at=str(combined.date),
        fee_scenario=combined.fee_scenario,
        fee_bullets=combined.explanation_bullets,
        fee_sources=combined.source_links,
        fee_last_checked=str(combined.last_checked),
    )


# ── Public API ─────────────────────────────────────────────────────────────────

def create_gmail_draft(combined: Any) -> str:
    """
    Create a Gmail draft with the weekly pulse + fee explanation.

    Parameters
    ----------
    combined : CombinedReport
        Output of phase4.combined.combine().

    Returns
    -------
    str
        URL to the Gmail drafts folder, or "" if skipped/failed.

    Notes
    -----
    - Returns "" silently if GMAIL_CLIENT_SECRET is not set.
    - Non-fatal: logs warning on failure, does not crash the pipeline.
    - Creates a DRAFT only — never auto-sends.
    """
    secret_path = os.path.expanduser(
        os.getenv("GMAIL_CLIENT_SECRET", "~/.groww/gmail_client_secret.json")
    )
    print(f"[GMAIL DEBUG] secret_path={secret_path} exists={os.path.exists(secret_path)}", flush=True)
    if not os.path.exists(secret_path):
        print(f"[GMAIL DEBUG] GMAIL_CLIENT_SECRET not found at {secret_path} — skipping", flush=True)
        return ""

    email_to = os.getenv("EMAIL_TO", "")
    print(f"[GMAIL DEBUG] EMAIL_TO={email_to!r}", flush=True)
    if not email_to:
        print("[GMAIL DEBUG] EMAIL_TO not set — skipping", flush=True)
        return ""

    try:
        from googleapiclient.discovery import build

        creds   = _get_gmail_credentials()
        service = build("gmail", "v1", credentials=creds, cache_discovery=False)

        wp      = combined.weekly_pulse
        subject = f"Weekly Pulse + Fee Explainer — {wp.week_label}"
        plain   = _build_plain_body(combined)
        html    = _build_html_body(combined)

        # Build MIME message — plain fallback + HTML primary
        msg            = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["To"]      = email_to
        msg.attach(MIMEText(plain, "plain", "utf-8"))
        msg.attach(MIMEText(html,  "html",  "utf-8"))

        # Encode and send directly to inbox
        raw  = base64.urlsafe_b64encode(msg.as_bytes()).decode("utf-8")
        sent = service.users().messages().send(
            userId="me",
            body={"raw": raw},
        ).execute()

        msg_id   = sent.get("id", "")
        sent_url = f"https://mail.google.com/mail/u/0/#inbox"
        logger.info("Gmail sent — id: %s | subject: %r", msg_id, subject)
        return sent_url

    except Exception as exc:
        logger.error("Gmail send failed: %s", exc, exc_info=True)
        return ""
